import type { Metadata } from "next";
import "./globals.css";
import styles from './layout.module.css'
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body>
        <Providers>
          <div className={styles.page}>
            <header className={styles.header}>
              <h1>Todo App</h1>
            </header>
            <main className={styles.main}>
              <div className={styles.container}>
                {children}
              </div>
            </main>
          </div>
        </Providers>
      </body>
    </html>

  );
}
